version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: invoice-app-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - overlay
    ports:
      - "5430:5432"
    command: postgres -p 5432

volumes:
  pgdata:

networks:
  overlay:
    driver: bridge
