# version: "3"
# services:
#   postgres:
#     image: postgres:alpine
#     container_name: invoice-app-backend
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - overlay
#     ports:
#       - "5430:5432" # 기본 PostgreSQL 포트
#     command: postgres -p 5432 # 포트 매핑을 위한 명령어

# volumes:
#   pgdata:

# networks:
#   overlay:
#     driver: bridge

version: "3"

services:
  backend:
    build: .
    container_name: invoice-app-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL} # Railway DB 연결
    networks:
      - overlay
    ports:
      - "8000:8000" # 백엔드 포트 설정

networks:
  overlay:
    driver: bridge
